import About from '@/components/about'
import Contact from '@/components/contact'
import Experience from '@/components/experience'
import Hero from '@/components/hero'
import Navbar from '@/components/navbar'
import OtherProjects from '@/components/other-projects'
import Projects from '@/components/projects'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Marcos Ochieng</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-primary'>
        <Navbar />
        <Hero />
        <About />
        <Experience />
        <Projects />
        <OtherProjects />
        <Contact />
      </main>
    </>
  )
}
